package org.cb.zframe.auth.web.controller;

import java.util.ArrayList;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import org.cb.zframe.auth.Org;
import org.cb.zframe.dao.QueryObject;
import org.cb.zframe.service.GenericManager;
import org.cb.zframe.web.util.PageUtil;

/**
 * Handle View (ViewObject ViewList QueryList BatchDelete)<br>
 * Freemarker AutoGenerated
 * 
 * @date 2009-03-11 14:21:55 
 * 
 */
@Controller
public class OrgController {
	private final Logger log = LoggerFactory.getLogger(getClass());
	@Autowired
	@Qualifier("orgManager")
	private GenericManager<Org, Long> orgManager;

	public void setOrgManager(GenericManager<Org, Long> orgManager) {
		this.orgManager = orgManager;
	}
	
	/**
	 * ViewObjectById
	 * 
	 * @param id
	 * @param model
	 */
	@RequestMapping("/org.do")
	public String viewOrg(@RequestParam("id") Long id, Model model) {
		Org org = orgManager.get(id);
		model.addAttribute(org);
		return "auth/org"; 
	}
	
	/**
	 * ListView 
	 * 
	 * @param request 
	 * @param model 
	 */
	@RequestMapping("/orgList.do")
	public String viewOrgList(HttpServletRequest request, Model model)
			throws Exception {	
		PageUtil page = new PageUtil(orgManager);
		//String queryName = (String) request.getParameter("queryName");
		List<QueryObject> l = new ArrayList<QueryObject>();
			
		/* TODO add your Query here*/
		/*if (queryName != null && queryName.length() != 0) {
			QueryObject q = new QueryObject("description", QueryObject.LIKE,
					queryName + "%", QueryObject.STR);
			l.add(q);
		}*/
		page.setPageObjectToModel(request, model, l);
		return "auth/orgList";
	}
	
	/**
	 * Batch delete items
	 *
	 * @param request
	 * @param model
	 * @return
	 * @throws Exception
	 */
	@RequestMapping("/deleteOrgList.do")
	public String deleteOrgList(HttpServletRequest request, Model model)
			throws Exception {
		String[] items = request.getParameterValues("item");
		if (items != null && items.length > 0) {
			Long[] ids = new Long[items.length];
			for (int i = 0; i < items.length; i++) {
				ids[i] = Long.valueOf(items[i]);
			}
			orgManager.delete(ids, false);	
			logDelete(ids);	
		}
		//to viewList
		return viewOrgList(request, model);
	}	
	
	private void logDelete(Long[] ids) {
		if (log.isDebugEnabled()) {
			StringBuffer sb = new StringBuffer("delete orgList ids:");
			for (int i = 0; i < ids.length; i++) {
				sb.append(ids[i]).append(",");			
			}
			log.debug(sb.toString());
		}
	}
}
