package org.cb.zframe.auth.web.controller;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import org.cb.zframe.auth.Org;
import org.cb.zframe.service.GenericManager;

/**
 * Handle Form (New Update Delete)<br>
 * Freemarker AutoGenerated
 * 
 * @date 2009-03-11 14:21:55 
 * 
 */
@Controller
@RequestMapping("/orgForm.do")
public class OrgForm {
	private final Logger log = LoggerFactory.getLogger(getClass());

	@Autowired
	@Qualifier("orgManager")
	private GenericManager<Org, Long> orgManager;

	public void setOrgManager(GenericManager<Org, Long> orgManager) {
		this.orgManager = orgManager;
	} 
	
	
	/**
	 * Enter form page(get the object if exist or just new one)
	 * 
	 * @param id
	 * @param model
	 */
	@RequestMapping(method = RequestMethod.GET)
	public String setupForm(
			@RequestParam(value = "id", required = false) Long id,
			ModelMap model) {
		Org org;
		if (id == null || id == 0L) {
			org = new Org();
		} else {
			org = orgManager.get(id);
		}
		model.addAttribute("org",org);
		return "auth/orgForm";

	}
 
 	/**
	 * Submit(save or delete)
	 * 
	 * @param org
	 * @param delete
	 * @param result
	 * @param status
	 * @return
	 */
	@RequestMapping(method = RequestMethod.POST)
	public String processSubmit(@ModelAttribute("org") Org org,
			@RequestParam(value = "delete", required = false) String delete,
			HttpServletRequest request) {
		if (delete != null) {
			orgManager.delete(org.getId());
			log.debug("delete org id:"+org.getId());
			return "redirect:orgList.do";
		} else {		
			String action=org.getId()==0?"new":"update";		
			org = orgManager.save(org);
			log.debug(action+" org id:"+org.getId());
			return "redirect:orgList.do";
		}
	}
}