package org.cb.zframe.sample.web.controller;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import org.cb.zframe.sample.Computer;
import org.cb.zframe.sample.Person;
import org.cb.zframe.service.GenericManager;

/**
 * Handle Form (New Update Delete)<br>
 * Freemarker AutoGenerated
 * 
 * @date 2009-03-13 16:46:15 
 * 
 */
@Controller
@RequestMapping("/computerForm.do")
public class ComputerForm {
	private final Logger log = LoggerFactory.getLogger(getClass());

	@Autowired
	@Qualifier("computerManager")
	private GenericManager<Computer, Long> computerManager;

	public void setComputerManager(GenericManager<Computer, Long> computerManager) {
		this.computerManager = computerManager;
	} 
		
	@Autowired
	@Qualifier("personManager")
	private GenericManager<Person, Long> personManager;
	
	public void setPersonManager(GenericManager<Person, Long> personManager) {
		this.personManager = personManager;
	}
	
	@InitBinder
    public void setAllowedFields(WebDataBinder dataBinder) {
        dataBinder.setDisallowedFields(new String[] {"person",});
    }
	
	/**
	 * Enter form page(get the object if exist or just new one)
	 * 
	 * @param id
	 * @param model
	 */
	@RequestMapping(method = RequestMethod.GET)
	public String setupForm(
			@RequestParam(value = "id", required = false) Long id,
			ModelMap model) {
		Computer computer;
		if (id == null || id == 0L) {
			computer = new Computer();
		} else {
			computer = computerManager.get(id);
		}
		model.addAttribute("computer",computer);
		
		
		
			List<Person> personList=personManager.getAll();
			model.addAttribute("personList",personList);
		
		return "sample/computerForm";

	}
 
 	/**
	 * Submit(save or delete)
	 * 
	 * @param computer
	 * @param delete
	 * @param result
	 * @param status
	 * @return
	 */
	@RequestMapping(method = RequestMethod.POST)
	public String processSubmit(@ModelAttribute("computer") Computer computer,
			@RequestParam(value = "delete", required = false) String delete,
			HttpServletRequest request) {
		if (delete != null) {
			computerManager.delete(computer.getId());
			log.debug("delete computer id:"+computer.getId());
			return "redirect:computerList.do";
		} else {		
			String action=computer.getId()==0?"new":"update";		
			
			Person person=personManager.get(Long.valueOf(request.getParameter("person")));  
			computer.setPerson(person);
			computer = computerManager.save(computer);
			log.debug(action+" computer id:"+computer.getId());
			return "redirect:computerList.do";
		}
	}
}