package org.cb.zframe.sample.web.controller;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import org.cb.zframe.sample.Person;
import org.cb.zframe.service.GenericManager;

/**
 * Handle Form (New Update Delete)<br>
 * Freemarker AutoGenerated
 * 
 * @date 2009-03-13 16:46:16 
 * 
 */
@Controller
@RequestMapping("/personForm.do")
public class PersonForm {
	private final Logger log = LoggerFactory.getLogger(getClass());

	@Autowired
	@Qualifier("personManager")
	private GenericManager<Person, Long> personManager;

	public void setPersonManager(GenericManager<Person, Long> personManager) {
		this.personManager = personManager;
	} 
	
	
	/**
	 * Enter form page(get the object if exist or just new one)
	 * 
	 * @param id
	 * @param model
	 */
	@RequestMapping(method = RequestMethod.GET)
	public String setupForm(
			@RequestParam(value = "id", required = false) Long id,
			ModelMap model) {
		Person person;
		if (id == null || id == 0L) {
			person = new Person();
		} else {
			person = personManager.get(id);
		}
		model.addAttribute("person",person);
		
		
		
		
		
		
		
		return "sample/personForm";

	}
 
 	/**
	 * Submit(save or delete)
	 * 
	 * @param person
	 * @param delete
	 * @param result
	 * @param status
	 * @return
	 */
	@RequestMapping(method = RequestMethod.POST)
	public String processSubmit(@ModelAttribute("person") Person person,
			@RequestParam(value = "delete", required = false) String delete,
			HttpServletRequest request) {
		if (delete != null) {
			personManager.delete(person.getId());
			log.debug("delete person id:"+person.getId());
			return "redirect:personList.do";
		} else {		
			String action=person.getId()==0?"new":"update";		
			person = personManager.save(person);
			log.debug(action+" person id:"+person.getId());
			return "redirect:personList.do";
		}
	}
}