package org.cb.zframe.sample.web.controller;

import java.util.ArrayList;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import org.cb.zframe.dao.QueryObject;
import org.cb.zframe.sample.Person;
import org.cb.zframe.service.GenericManager;
import org.cb.zframe.web.util.PageUtil;

/**
 * Handle View (ViewObject ViewList QueryList BatchDelete)<br>
 * Freemarker AutoGenerated
 * 
 * @date 2009-03-13 16:46:16 
 * 
 */
@Controller
public class PersonController {
	private final Logger log = LoggerFactory.getLogger(getClass());
	@Autowired
	@Qualifier("personManager")
	private GenericManager<Person, Long> personManager;

	public void setPersonManager(GenericManager<Person, Long> personManager) {
		this.personManager = personManager;
	}
	
	/**
	 * ViewObjectById
	 * 
	 * @param id
	 * @param model
	 */
	@RequestMapping("/person.do")
	public String viewPerson(@RequestParam("id") Long id, Model model) {
		Person person = personManager.get(id);
		model.addAttribute(person);
		return "sample/person"; 
	}
	
	/**
	 * ListView 
	 * 
	 * @param request 
	 * @param model 
	 */
	@RequestMapping("/personList.do")
	public String viewPersonList(HttpServletRequest request, Model model)
			throws Exception {	
		PageUtil page = new PageUtil(personManager);
		//String queryName = (String) request.getParameter("queryName");
		List<QueryObject> l = new ArrayList<QueryObject>();
			
		/* TODO add your Query here*/
		/*if (queryName != null && queryName.length() != 0) {
			QueryObject q = new QueryObject("description", QueryObject.LIKE,
					queryName + "%", QueryObject.STR);
			l.add(q);
		}*/
		page.setPageObjectToModel(request, model, l);
		return "sample/personList";
	}
	
	/**
	 * Batch delete items
	 *
	 * @param request
	 * @param model
	 * @return
	 * @throws Exception
	 */
	@RequestMapping("/deletePersonList.do")
	public String deletePersonList(HttpServletRequest request, Model model)
			throws Exception {
		String[] items = request.getParameterValues("item");
		if (items != null && items.length > 0) {
			Long[] ids = new Long[items.length];
			for (int i = 0; i < items.length; i++) {
				ids[i] = Long.valueOf(items[i]);
			}
			personManager.delete(ids, false);	
			logDelete(ids);	
		}
		//to viewList
		return viewPersonList(request, model);
	}	
	
	private void logDelete(Long[] ids) {
		if (log.isDebugEnabled()) {
			StringBuffer sb = new StringBuffer("delete personList ids:");
			for (int i = 0; i < ids.length; i++) {
				sb.append(ids[i]).append(",");			
			}
			log.debug(sb.toString());
		}
	}
}
