package org.cb.zframe.service;

import org.cb.zframe.auth.Org;
import org.cb.zframe.service.GenericManager;
/**
 * Manager test<br>
 * Freemarker AutoGenerated
 * 
 * @date 2009-03-11 14:21:55 
 * 
 */
public class OrgManagerTest extends BaseManagerTestCase {

	private GenericManager<Org, Long> orgManager;

	public void setOrgManager(GenericManager<Org, Long> orgManager) {
		this.orgManager = orgManager;
	}
	

	public void testAddUpdateAndRemove() throws Exception {
		Org org = new Org();
		org.setName("name1");	
		org.setSpell("spell1");	

		org = orgManager.save(org);
		assertEquals("name1", org.getName());
		assertEquals("spell1", org.getSpell());

		log.debug("update org...");
		org.setName("name2");	
		org.setSpell("spell2");	

		org = orgManager.get(org.getId());
		assertEquals("name2", org.getName());
		assertEquals("spell2", org.getSpell());

		log.debug("removing org...");

		orgManager.delete(org.getId());

		try {
			org = orgManager.get(org.getId());
			fail("Expected 'Exception' not thrown");
		} catch (Exception e) {
			log.debug(e.toString());
			assertNotNull(e);
		}
	}
}
