package ${class.rootPack}.dao;

import org.springframework.dao.DataAccessException;

import ${class.pack}.${class.name};

/**
 * Dao test<br>
 * Freemarker AutoGenerated
 * 
 * @date ${time} 
 * 
 */
public class ${class.name}DaoTest extends BaseDaoTestCase {
	private GenericDao<${class.name}, Long> ${class.spell}Dao = null;

	public void set${class.name}Dao(GenericDao<${class.name}, Long> ${class.spell}Dao) {
		this.${class.spell}Dao = ${class.spell}Dao;
	}

	public void testAddAndRemove() {
		${class.name} ${class.spell} = new ${class.name}();
		<#list class.fields as field>
			<#if field.name!="id">
		${class.spell}.set${field.upper}("${field}1");	
			</#if>
		</#list>	

		${class.spell} = ${class.spell}Dao.save(${class.spell});
		flush();

		${class.spell} = ${class.spell}Dao.get(${class.spell}.getId());
		
		<#list class.fields as field>
			<#if field.name!="id">
		assertEquals("${field}1", ${class.spell}.get${field.upper}());
			</#if>
		</#list>
		assertNotNull(${class.spell}.getId());

		log.debug("removing ${class.spell}...");
		${class.spell}Dao.delete(${class.spell}.getId());
		flush();
		try {
			${class.spell}Dao.get(${class.spell}.getId());
			fail("${class.spell} found in database");
		} catch (DataAccessException dae) {
			log.debug("Expected exception: " + dae.getMessage());
			assertNotNull(dae);
		}
	}
}
